# Generated by Django 3.0.7 on 2020-07-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20200630_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
